version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=admin123
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./docker-mysql-init.sql:/docker-entrypoint-initdb.d/docker-mysql-init.sql
volumes:
  db:
    driver: local