desafio-votacao-api:
   user-info-api-url: https://user-info.herokuapp.com
spring:
   main:
      allow-bean-definition-overriding: true
   application:
      name: desafio-votacao-api
   mvc:
      locale: pt_BR
      locale-resolver: fixed
   datasource:
      url: jdbc:mysql://localhost:3306/
      username: root
      password: admin123
   flyway:
      enabled: true
      url: jdbc:mysql://localhost:3306/
      username: root
      password: admin123
      locations: classpath:db/migration
      schemas: votacao
      table: flyway_schema_history
   jpa:
      hibernate:
         ddl-auto: none
      open-in-view: false
      properties:
         hibernate:
            default_schema: votacao
feign:
   client:
      config:
        default:
           loggerLevel: full

logging:
   level:
      root: info
      
management:
  endpoints:
    web:
      exposure:
        include: "*"